// Pure UI configuration constants no runtime data, no seed dependency.
// Previously scattered in demo-data-omnichannel.ts; moved here so pages
// can import channel/campaign config without touching demo files.

export const CHANNEL_CONFIG: Record<
  string,
  { label: string; color: string; bg: string; border: string; icon_color: string }
> = {
  email: {
    label: "Email",
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    border: "border-blue-500/20",
    icon_color: "#3B82F6",
  },
  phone: {
    label: "Phone",
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/20",
    icon_color: "#10B981",
  },
  whatsapp: {
    label: "WhatsApp",
    color: "text-green-500",
    bg: "bg-green-500/10",
    border: "border-green-500/20",
    icon_color: "#25D366",
  },
  telegram: {
    label: "Telegram",
    color: "text-sky-500",
    bg: "bg-sky-500/10",
    border: "border-sky-500/20",
    icon_color: "#26A5E4",
  },
  linkedin: {
    label: "LinkedIn",
    color: "text-indigo-500",
    bg: "bg-indigo-500/10",
    border: "border-indigo-500/20",
    icon_color: "#0A66C2",
  },
  meta_ads: {
    label: "Meta Ads",
    color: "text-violet-500",
    bg: "bg-violet-500/10",
    border: "border-violet-500/20",
    icon_color: "#0866FF",
  },
  warm_intro: {
    label: "Warm Intro",
    color: "text-amber-500",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    icon_color: "#F59E0B",
  },
};

export const CAMPAIGN_PLAY_TYPES = [
  {
    id: "warm_intro",
    title: "Warm Intro Campaign",
    description:
      "Route outreach through your team's warmest relationship paths. Best for high-value accounts.",
    best_for: "Enterprise, strategic accounts",
    channels: ["email", "linkedin"] as const,
    effort: "moderate" as const,
    impact: "high" as const,
    risk: "low" as const,
    icon: "🤝",
    color: "text-amber-500",
    bg: "bg-amber-500/10",
  },
  {
    id: "phone_first_blitz",
    title: "Phone-First Blitz",
    description:
      "Lead with personalized calls using AI-generated scripts. Follow up via email and WhatsApp.",
    best_for: "High-intent signals, urgent pipeline",
    channels: ["phone", "email", "whatsapp"] as const,
    effort: "hard" as const,
    impact: "high" as const,
    risk: "low" as const,
    icon: "📞",
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
  },
  {
    id: "whatsapp_followup",
    title: "WhatsApp Follow-Up",
    description: "Re-engage demo no-shows and stalled deals via WhatsApp with compliant templates.",
    best_for: "Demo no-shows, 7-14 day follow-up",
    channels: ["whatsapp", "email"] as const,
    effort: "easy" as const,
    impact: "high" as const,
    risk: "low" as const,
    icon: "💬",
    color: "text-green-500",
    bg: "bg-green-500/10",
  },
  {
    id: "meta_retargeting",
    title: "Meta Retargeting",
    description:
      "Reach decision-makers on Facebook & Instagram who visited your pricing or competitor pages.",
    best_for: "Website visitors, intent signals",
    channels: ["meta_ads", "email"] as const,
    effort: "easy" as const,
    impact: "medium" as const,
    risk: "low" as const,
    icon: "📣",
    color: "text-violet-500",
    bg: "bg-violet-500/10",
  },
  {
    id: "signal_based_outbound",
    title: "Signal-Based Outbound",
    description:
      "Trigger personalized outreach the moment a buying signal fires funding, hiring, leadership change.",
    best_for: "Fresh signals, competitive timing",
    channels: ["email", "linkedin", "phone"] as const,
    effort: "moderate" as const,
    impact: "high" as const,
    risk: "low" as const,
    icon: "⚡",
    color: "text-blue-500",
    bg: "bg-blue-500/10",
  },
  {
    id: "competitor_displacement",
    title: "Competitor Displacement",
    description:
      "Target accounts showing competitor intent job postings mentioning Apollo, Outreach, Clay.",
    best_for: "Competitor accounts, displacement plays",
    channels: ["email", "linkedin", "phone"] as const,
    effort: "hard" as const,
    impact: "high" as const,
    risk: "medium" as const,
    icon: "🎯",
    color: "text-red-500",
    bg: "bg-red-500/10",
  },
  {
    id: "linkedin_email_sequence",
    title: "LinkedIn + Email Sequence",
    description:
      "Multi-touch sequence starting with LinkedIn connection, followed by email cadence.",
    best_for: "SMB, SDR-led motion",
    channels: ["linkedin", "email"] as const,
    effort: "moderate" as const,
    impact: "medium" as const,
    risk: "low" as const,
    icon: "🔗",
    color: "text-indigo-500",
    bg: "bg-indigo-500/10",
  },
  {
    id: "lost_deal_revival",
    title: "Lost Deal Revival",
    description:
      "Re-engage closed-lost accounts with new signal hooks leadership change, funding, new pain.",
    best_for: "Lost deals 90-180 days old",
    channels: ["email", "phone", "whatsapp"] as const,
    effort: "moderate" as const,
    impact: "high" as const,
    risk: "low" as const,
    icon: "🔄",
    color: "text-orange-500",
    bg: "bg-orange-500/10",
  },
  {
    id: "event_webinar_invite",
    title: "Webinar / Event Invite",
    description:
      "Invite warm-path accounts to a webinar, roundtable, or live event. Soft touch, high value.",
    best_for: "Mid-funnel nurture, authority building",
    channels: ["email", "linkedin", "telegram"] as const,
    effort: "easy" as const,
    impact: "medium" as const,
    risk: "low" as const,
    icon: "🎪",
    color: "text-pink-500",
    bg: "bg-pink-500/10",
  },
];

export const CAMPAIGN_GOALS = [
  {
    id: "book_meetings",
    label: "Book meetings",
    icon: "📅",
    description: "Drive calendar bookings with high-intent accounts",
  },
  {
    id: "revive_stalled_deals",
    label: "Revive stalled deals",
    icon: "🔄",
    description: "Re-engage accounts that went quiet",
  },
  {
    id: "post_demo_followup",
    label: "Follow up after demo",
    icon: "✅",
    description: "Move demo attendees to next stage",
  },
  {
    id: "reengage_old_leads",
    label: "Re-engage old leads",
    icon: "💤",
    description: "Wake up leads dormant 90+ days",
  },
  {
    id: "new_segment_launch",
    label: "Launch into new segment",
    icon: "🚀",
    description: "Enter a new vertical or persona",
  },
  {
    id: "convert_website_visitors",
    label: "Convert website visitors",
    icon: "🌐",
    description: "Convert pricing page + intent signals",
  },
  {
    id: "win_competitor_accounts",
    label: "Win competitor accounts",
    icon: "🎯",
    description: "Displace Apollo, Outreach, Clay users",
  },
  {
    id: "promote_webinar",
    label: "Promote webinar / event",
    icon: "🎪",
    description: "Drive registrations for an upcoming event",
  },
  {
    id: "retarget_warm_accounts",
    label: "Retarget warm accounts",
    icon: "🎣",
    description: "Multi-channel retargeting for interested accounts",
  },
  {
    id: "expand_existing_accounts",
    label: "Expand existing accounts",
    icon: "📈",
    description: "Upsell or cross-sell existing customers",
  },
];
