/**
 * Extended demo data workspace, KB, audit, AI usage, test scenarios,
 * plus 15 additional accounts and 40+ additional contacts.
 */

import type {
  Account,
  AIUsageLog,
  AuditLog,
  Contact,
  KnowledgeBaseItem,
  UserTestScenario,
  Workspace,
  WorkspaceAISettings,
  WorkspaceMember,
} from "@/types";

const ago = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => ago(d * 24);

// ─── Workspace ─────────────────────────────────────────────────────────────

export const DEMO_WORKSPACE: Workspace = {
  id: "ws-1",
  name: "WarmPath",
  domain: "warmpath.ai",
  industry: "AI / Sales Tech",
  company_size: "1–10",
  website: "https://warmpath.ai",
  description:
    "AI-powered warm outbound sales agent that routes outreach through your team's relationship graph, surfaces buying signals, and generates fact-checked messages in your voice.",
  plan: "growth",
  onboarding_stage: "complete",
  created_at: daysAgo(110),
};

export const DEMO_WORKSPACE_MEMBERS: WorkspaceMember[] = [
  {
    id: "wm-1",
    workspace_id: "ws-1",
    user_id: "user-1",
    name: "Adhik Agarwal",
    email: "adhik@warmpath.ai",
    role: "owner",
    joined_at: daysAgo(110),
    title: "Founder & CEO",
    connected_sources: ["gmail", "linkedin", "google_calendar"],
    relationship_score: 95,
  },
  {
    id: "wm-2",
    workspace_id: "ws-1",
    user_id: "tm-2",
    name: "Sarah Chen",
    email: "sarah@warmpath.ai",
    role: "admin",
    invited_by: "user-1",
    joined_at: daysAgo(90),
    title: "Advisor Ex-Salesforce",
    connected_sources: ["gmail", "linkedin", "salesforce"],
    relationship_score: 88,
  },
  {
    id: "wm-3",
    workspace_id: "ws-1",
    user_id: "tm-3",
    name: "Rohan Mehta",
    email: "rohan@warmpath.ai",
    role: "sales_rep",
    invited_by: "user-1",
    joined_at: daysAgo(85),
    title: "Co-Founder",
    connected_sources: ["gmail", "linkedin"],
    relationship_score: 82,
  },
  {
    id: "wm-4",
    workspace_id: "ws-1",
    user_id: "tm-4",
    name: "Maya Iyer",
    email: "maya@warmpath.ai",
    role: "sales_rep",
    invited_by: "user-1",
    joined_at: daysAgo(60),
    title: "Sales Consultant",
    connected_sources: ["outlook", "linkedin", "hubspot"],
    relationship_score: 76,
  },
];

// ─── AI Settings ───────────────────────────────────────────────────────────

export const DEMO_AI_SETTINGS: WorkspaceAISettings = {
  workspace_id: "ws-1",
  ai_mode: "mock",
  monthly_budget_usd: 50,
  usage_this_month_usd: 0,
  allow_remote_generation: false,
  require_approval_for_remote: true,
  fallback_to_mock: true,
  provider: "mock",
  model: "warmpath-mock-v1",
};

// ─── Knowledge Base ────────────────────────────────────────────────────────

export const DEMO_KB_ITEMS: KnowledgeBaseItem[] = [
  {
    id: "kb-1",
    workspace_id: "ws-1",
    title: "WarmPath Product Overview",
    type: "product",
    content:
      "WarmPath is an AI GTM sales agent that turns cold prospects into warm intros by mapping your team's full relationship graph, detecting buying signals in real time, and routing outreach through the warmest path. Unlike generic AI SDR tools, every message is grounded in your knowledge base and requires human approval before sending so no hallucinations, no brand risk.",
    source: "Internal product team",
    tags: ["product", "overview", "pitch", "ai"],
    confidence_score: 98,
    approved_for_ai: true,
    created_at: daysAgo(90),
    updated_at: daysAgo(5),
    used_in_messages: 12,
  },
  {
    id: "kb-2",
    workspace_id: "ws-1",
    title: "Core Value Proposition Warm Path ROI",
    type: "value_prop",
    content:
      "Warm intros produce 5× higher reply rates and 3× higher close rates vs cold outbound (Gartner, 2025). WarmPath automates the warm-path discovery process finding the shortest relationship route between your team and any target prospect. Teams using WarmPath go live in under 5 minutes and see first meetings booked within 48 hours.",
    source: "Sales team + Gartner research",
    tags: ["value-prop", "roi", "stats", "warm-path"],
    confidence_score: 95,
    approved_for_ai: true,
    created_at: daysAgo(88),
    updated_at: daysAgo(3),
    used_in_messages: 18,
  },
  {
    id: "kb-3",
    workspace_id: "ws-1",
    title: "Pricing Growth Plan Details",
    type: "pricing",
    content:
      "Growth plan is $149/month. Includes: 50 target accounts, unlimited AI-generated messages, all 13 signal types, full relationship graph, campaign automation, Gmail + LinkedIn integration, HubSpot/Salesforce sync, and the HITL approval queue. Free plan: 5 accounts, 25 messages/month. Scale plan ($399/month): unlimited accounts, multi-rep persona engine, full team graph, custom signals, API access.",
    source: "Billing page",
    tags: ["pricing", "plans", "growth", "scale", "free"],
    confidence_score: 100,
    approved_for_ai: true,
    created_at: daysAgo(85),
    updated_at: daysAgo(2),
    used_in_messages: 3,
  },
  {
    id: "kb-4",
    workspace_id: "ws-1",
    title: "Ideal Customer Profile (ICP)",
    type: "icp",
    content:
      "ICP: B2B SaaS companies, Series A through Series C, 50–500 employees, ARR $5M–$100M. Verticals: Sales Tech, RevOps, FinTech, Analytics, HR Tech, DevTools, MarTech. Buyer personas: VP of Sales, CRO, Head of Revenue, Founder/CEO at earlier-stage. Pain points: low reply rates on cold outbound, manual intro routing, lack of signal visibility, SDR ramp time. Budget: $5K–$50K/year. Decision timeline: 2–4 weeks.",
    source: "GTM strategy doc",
    tags: ["icp", "buyer-persona", "target-market"],
    confidence_score: 92,
    approved_for_ai: true,
    created_at: daysAgo(80),
    updated_at: daysAgo(10),
    used_in_messages: 9,
  },
  {
    id: "kb-5",
    workspace_id: "ws-1",
    title: "Competitor Battlecard Apollo vs WarmPath",
    type: "competitor",
    content:
      "Apollo: Strong prospecting database, weak on relationship intelligence and warm routing. Apollo gives you emails; we give you warm intros. Key WarmPath advantages: relationship graph (Apollo has none), warm-path routing (manual in Apollo), knowledge-grounded messages (Apollo templates only), human approval loop (Apollo auto-sends), real-time signal detection (Apollo basic intent data). When prospect says 'we use Apollo': 'Apollo is great for discovery we complement it. Connect your Apollo lists to WarmPath and let us route outreach through warm paths instead of cold sequences.'",
    source: "Sales team competitive intelligence",
    tags: ["competitor", "apollo", "battlecard"],
    confidence_score: 88,
    approved_for_ai: true,
    created_at: daysAgo(75),
    updated_at: daysAgo(15),
    used_in_messages: 2,
  },
  {
    id: "kb-6",
    workspace_id: "ws-1",
    title: "Objection: 'We already have an AI SDR tool'",
    type: "objection",
    content:
      "Response: 'Most AI SDR tools are cold sequence automators they just send templated emails at scale. WarmPath is different: we map your team's relationship graph, find the warmest path to every prospect, and generate messages that reference those real relationships. Our messages are also grounded in your knowledge base and require your approval before sending so no hallucinations, no brand risk. The typical team using both says WarmPath handles the warm-path opportunities while their AI SDR handles cold fill-in.' Close: 'What's your current reply rate on cold sequences? Most teams see 3–5%. Our warm-path customers average 31%.'",
    source: "Sales call recordings",
    tags: ["objection", "ai-sdr", "response"],
    confidence_score: 90,
    approved_for_ai: true,
    created_at: daysAgo(70),
    updated_at: daysAgo(8),
    used_in_messages: 0,
  },
  {
    id: "kb-7",
    workspace_id: "ws-1",
    title: "Case Study SeriesAI (anonymized)",
    type: "case_study",
    content:
      "A Series A B2B SaaS company with 3 SDRs used WarmPath to increase outbound reply rates from 7% to 38% in 6 weeks. Key wins: (1) Found 14 warm paths through advisor network to target CROs; (2) Triggered by funding signal, booked 3 meetings within 72h of a competitor's raise; (3) SDRs saved ~4h/week on manual research. Quote: 'WarmPath found a warm path we had no idea existed our advisor was a former colleague of the CRO at our #1 target account.' CEO, SeriesAI (name withheld).",
    source: "Customer interview",
    tags: ["case-study", "roi", "series-a", "success-story"],
    confidence_score: 96,
    approved_for_ai: true,
    created_at: daysAgo(60),
    updated_at: daysAgo(20),
    used_in_messages: 7,
  },
  {
    id: "kb-8",
    workspace_id: "ws-1",
    title: "Approved Claims Verified Statistics",
    type: "compliance",
    content:
      "APPROVED TO USE IN MESSAGES: (1) Warm intros produce 5× higher reply rates vs cold email (Gartner, 2025). (2) 47% close rate on deals that started with a warm introduction (WarmPath customer data, n=400). (3) Setup takes under 5 minutes first warm lead identified before call ends. (4) Zero RevOps engineers required. (5) Human approval required before any message sends. These stats are verified and approved by legal for use in outreach.",
    source: "Legal + marketing review",
    tags: ["compliance", "approved-claims", "stats", "legal"],
    confidence_score: 100,
    approved_for_ai: true,
    created_at: daysAgo(55),
    updated_at: daysAgo(1),
    used_in_messages: 15,
  },
  {
    id: "kb-9",
    workspace_id: "ws-1",
    title: "Banned Claims Do NOT Use",
    type: "compliance",
    content:
      "DO NOT USE IN ANY MESSAGES: (1) Never claim 'guaranteed results' or 'guaranteed reply rate increase'. (2) Never state specific revenue numbers for prospects we haven't verified. (3) Never claim 'AI replaces your SDRs' our positioning is AI-augmented, not AI-replacement. (4) Never reference competitor products negatively by name without specific factual basis. (5) Never claim GDPR/SOC2 compliance without checking current certification status. (6) Never promise free trials not in current pricing. Flag these if seen in generated messages.",
    source: "Legal team",
    tags: ["compliance", "banned-claims", "legal", "risk"],
    confidence_score: 100,
    approved_for_ai: false,
    created_at: daysAgo(50),
    updated_at: daysAgo(1),
    used_in_messages: 0,
  },
  {
    id: "kb-10",
    workspace_id: "ws-1",
    title: "Sales Playbook Discovery Call Script",
    type: "playbook",
    content:
      "DISCOVERY CALL FRAMEWORK (SPICED for WarmPath): Situation: 'Walk me through your current outbound motion how are reps finding and reaching out to prospects today?' Pain: 'What's your average reply rate? How much time do SDRs spend on research and personalization per prospect?' Impact: 'If reply rates doubled, what would that mean for pipeline? What does a meeting cost in SDR time right now?' Critical event: 'Are you hiring more SDRs soon? Any pipeline goals for Q3?' Decision: 'Who else would be involved in evaluating a tool like this?' Close: 'Based on what you've shared, I think we can [specific outcome]. Can I send you a 5-minute demo video built around your team's actual network?'",
    source: "Sales team",
    tags: ["playbook", "discovery", "spiced", "call-script"],
    confidence_score: 85,
    approved_for_ai: false,
    created_at: daysAgo(45),
    updated_at: daysAgo(7),
    used_in_messages: 0,
  },
  {
    id: "kb-11",
    workspace_id: "ws-1",
    title: "Buyer Persona VP of Sales",
    type: "persona",
    content:
      "VP of Sales persona: Primary goal is pipeline and quota attainment. Frustrated by: poor SDR reply rates, manual prospecting, ramp time for new hires, lack of signal visibility. Responds well to: ROI metrics, time-to-first-meeting, comparison to current state, peer proof ('other VP Sales at [similar company] saw X'). Skeptical of: AI hype, vendor promises, tools that require RevOps to set up. Champion signals: job postings for SDRs, missing quota, new CRO hired, company funding. Best outreach: short email referencing specific signal + warm connection, CTA = 20-min demo. Avoid: long emails, feature lists, 'AI-powered' language without specifics.",
    source: "Sales team + customer interviews",
    tags: ["persona", "vp-sales", "buyer", "messaging"],
    confidence_score: 88,
    approved_for_ai: true,
    created_at: daysAgo(40),
    updated_at: daysAgo(5),
    used_in_messages: 4,
  },
  {
    id: "kb-12",
    workspace_id: "ws-1",
    title: "Email Example Funding Signal Trigger",
    type: "email_example",
    content:
      "Subject: Congrats on the raise scaling outbound?\n\nHi [Name],\n\nCongrats on the $[X]M [Series] impressive milestone, especially with [Lead VC] involved.\n\nWhen companies at [Company]'s stage raise and plan to grow GTM, the first bottleneck is usually outbound quality. Reps get hired, sequences get built, and then reply rates disappoint.\n\nWe're building something different a sales agent that routes every cold prospect through your team's actual relationship graph, so outreach feels warm from day one.\n\nWorth 15 minutes this week?\n\nAdhik\n\n[This email was grounded in: KB-7 (Case Study), KB-8 (Approved Claims), KB-2 (Value Prop)]",
    source: "Best-performing outreach examples",
    tags: ["email-example", "funding-trigger", "template"],
    confidence_score: 94,
    approved_for_ai: true,
    created_at: daysAgo(30),
    updated_at: daysAgo(2),
    used_in_messages: 6,
  },
];

// ─── Additional Accounts (15 more) ────────────────────────────────────────

export const DEMO_ACCOUNTS_EXTRA: Account[] = [
  {
    id: "acc-11",
    name: "PipelineAI",
    domain: "pipelineai.io",
    industry: "Sales Intelligence",
    employee_count: 78,
    location: "San Francisco, CA",
    description: "AI-powered pipeline forecasting and deal intelligence for B2B SaaS teams.",
    stage: "prospect",
    fit_score: 93,
    intent_score: 87,
    warmth_score: 62,
    opportunity_score: 85,
    created_at: daysAgo(25),
  },
  {
    id: "acc-12",
    name: "DataSync",
    domain: "datasync.dev",
    industry: "Data Integration",
    employee_count: 42,
    location: "Austin, TX",
    description: "Zero-code data pipeline builder for revenue and product teams.",
    stage: "prospect",
    fit_score: 81,
    intent_score: 76,
    warmth_score: 55,
    opportunity_score: 73,
    created_at: daysAgo(22),
  },
  {
    id: "acc-13",
    name: "MarketerIQ",
    domain: "marketeriq.com",
    industry: "MarTech",
    employee_count: 168,
    location: "New York, NY",
    description: "AI marketing operations platform from demand gen to attribution.",
    stage: "engaged",
    fit_score: 88,
    intent_score: 84,
    warmth_score: 79,
    opportunity_score: 84,
    created_at: daysAgo(20),
  },
  {
    id: "acc-14",
    name: "SalesIQ",
    domain: "salesiq.ai",
    industry: "Revenue Intelligence",
    employee_count: 92,
    location: "Boston, MA",
    description: "Conversation intelligence and deal review platform for sales managers.",
    stage: "prospect",
    fit_score: 90,
    intent_score: 88,
    warmth_score: 71,
    opportunity_score: 83,
    created_at: daysAgo(18),
  },
  {
    id: "acc-15",
    name: "CloudPilot",
    domain: "cloudpilot.io",
    industry: "Cloud Ops",
    employee_count: 134,
    location: "Denver, CO",
    description: "Cloud cost optimization and infrastructure management for engineering teams.",
    stage: "prospect",
    fit_score: 77,
    intent_score: 73,
    warmth_score: 68,
    opportunity_score: 73,
    created_at: daysAgo(16),
  },
  {
    id: "acc-16",
    name: "HireFlow",
    domain: "hireflow.ai",
    industry: "HR Tech",
    employee_count: 58,
    location: "Chicago, IL",
    description: "AI recruiting automation platform from JD to hire in record time.",
    stage: "prospect",
    fit_score: 82,
    intent_score: 79,
    warmth_score: 60,
    opportunity_score: 75,
    created_at: daysAgo(15),
  },
  {
    id: "acc-17",
    name: "InsightHQ",
    domain: "insighthq.io",
    industry: "Business Intelligence",
    employee_count: 198,
    location: "Seattle, WA",
    description: "Self-serve BI platform built for GTM teams no SQL required.",
    stage: "engaged",
    fit_score: 86,
    intent_score: 91,
    warmth_score: 74,
    opportunity_score: 83,
    created_at: daysAgo(12),
  },
  {
    id: "acc-18",
    name: "PayStream",
    domain: "paystream.io",
    industry: "Payments",
    employee_count: 74,
    location: "Miami, FL",
    description: "Embedded payment infrastructure for SaaS and marketplace platforms.",
    stage: "prospect",
    fit_score: 79,
    intent_score: 72,
    warmth_score: 63,
    opportunity_score: 72,
    created_at: daysAgo(10),
  },
  {
    id: "acc-19",
    name: "TrustGraph",
    domain: "trustgraph.ai",
    industry: "Cybersecurity",
    employee_count: 112,
    location: "Austin, TX",
    description: "Identity and access security graph for enterprise SaaS environments.",
    stage: "prospect",
    fit_score: 75,
    intent_score: 68,
    warmth_score: 57,
    opportunity_score: 68,
    created_at: daysAgo(9),
  },
  {
    id: "acc-20",
    name: "FluxOps",
    domain: "fluxops.io",
    industry: "Workflow Automation",
    employee_count: 83,
    location: "San Francisco, CA",
    description: "No-code workflow automation for revenue and customer success teams.",
    stage: "prospect",
    fit_score: 91,
    intent_score: 86,
    warmth_score: 82,
    opportunity_score: 86,
    created_at: daysAgo(8),
  },
  {
    id: "acc-21",
    name: "DataRovers",
    domain: "datarovers.com",
    industry: "Data Enrichment",
    employee_count: 63,
    location: "New York, NY",
    description: "B2B data enrichment and ICP scoring platform for GTM teams.",
    stage: "prospect",
    fit_score: 89,
    intent_score: 83,
    warmth_score: 67,
    opportunity_score: 80,
    created_at: daysAgo(7),
  },
  {
    id: "acc-22",
    name: "TeamSync",
    domain: "teamsync.io",
    industry: "Team Collaboration",
    employee_count: 97,
    location: "Denver, CO",
    description: "Sales team collaboration and meeting intelligence platform.",
    stage: "engaged",
    fit_score: 84,
    intent_score: 78,
    warmth_score: 73,
    opportunity_score: 78,
    created_at: daysAgo(6),
  },
  {
    id: "acc-23",
    name: "RevenueIQ",
    domain: "revenueiq.ai",
    industry: "RevOps",
    employee_count: 152,
    location: "Boston, MA",
    description: "Revenue operations platform CRM hygiene, forecasting, and attribution.",
    stage: "prospect",
    fit_score: 95,
    intent_score: 92,
    warmth_score: 76,
    opportunity_score: 90,
    created_at: daysAgo(5),
  },
  {
    id: "acc-24",
    name: "LeadMesh",
    domain: "leadmesh.io",
    industry: "Lead Generation",
    employee_count: 71,
    location: "Chicago, IL",
    description: "B2B lead generation and intent data platform for sales teams.",
    stage: "prospect",
    fit_score: 86,
    intent_score: 89,
    warmth_score: 65,
    opportunity_score: 80,
    created_at: daysAgo(4),
  },
  {
    id: "acc-25",
    name: "GrowthEngine",
    domain: "growthengine.ai",
    industry: "Growth Platform",
    employee_count: 187,
    location: "San Francisco, CA",
    description: "AI-native growth platform from acquisition to expansion revenue.",
    stage: "prospect",
    fit_score: 94,
    intent_score: 90,
    warmth_score: 71,
    opportunity_score: 88,
    created_at: daysAgo(3),
  },
];

// ─── Additional Contacts (3 per new account = 45 contacts) ───────────────

export const DEMO_CONTACTS_EXTRA: Contact[] = [
  // PipelineAI (acc-11)
  {
    id: "con-13",
    account_id: "acc-11",
    name: "Ethan Brooks",
    email: "ethan@pipelineai.io",
    title: "VP of Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 93,
    warmth_score: 62,
    engagement_score: 58,
  },
  {
    id: "con-14",
    account_id: "acc-11",
    name: "Priya Nair",
    email: "priya.n@pipelineai.io",
    title: "Head of RevOps",
    seniority: "director",
    department: "RevOps",
    persona: "RevOps Builder",
    fit_score: 88,
    warmth_score: 55,
    engagement_score: 52,
  },
  // DataSync (acc-12)
  {
    id: "con-15",
    account_id: "acc-12",
    name: "Carlos Reyes",
    email: "carlos@datasync.dev",
    title: "CEO & Co-Founder",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 81,
    warmth_score: 55,
    engagement_score: 61,
  },
  {
    id: "con-16",
    account_id: "acc-12",
    name: "Nadia Kim",
    email: "nadia@datasync.dev",
    title: "VP Growth",
    seniority: "vp",
    department: "Growth",
    persona: "Growth Leader",
    fit_score: 79,
    warmth_score: 48,
    engagement_score: 44,
  },
  // MarketerIQ (acc-13)
  {
    id: "con-17",
    account_id: "acc-13",
    name: "Jordan Lee",
    email: "jordan@marketeriq.com",
    title: "CRO",
    seniority: "c_suite",
    department: "Revenue",
    persona: "Revenue Leader",
    fit_score: 88,
    warmth_score: 79,
    engagement_score: 73,
  },
  {
    id: "con-18",
    account_id: "acc-13",
    name: "Fatima Al-Hassan",
    email: "fatima@marketeriq.com",
    title: "Director of Sales",
    seniority: "director",
    department: "Sales",
    persona: "Sales Manager",
    fit_score: 85,
    warmth_score: 72,
    engagement_score: 68,
  },
  {
    id: "con-19",
    account_id: "acc-13",
    name: "Ryan Cho",
    email: "ryan@marketeriq.com",
    title: "Head of Demand Gen",
    seniority: "director",
    department: "Marketing",
    persona: "Marketing Leader",
    fit_score: 82,
    warmth_score: 66,
    engagement_score: 60,
  },
  // SalesIQ (acc-14)
  {
    id: "con-20",
    account_id: "acc-14",
    name: "Isabel Fontaine",
    email: "isabel@salesiq.ai",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 90,
    warmth_score: 71,
    engagement_score: 67,
  },
  {
    id: "con-21",
    account_id: "acc-14",
    name: "Marcus Bell",
    email: "marcus.b@salesiq.ai",
    title: "CEO",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 87,
    warmth_score: 65,
    engagement_score: 59,
  },
  // CloudPilot (acc-15)
  {
    id: "con-22",
    account_id: "acc-15",
    name: "Shreya Mishra",
    email: "shreya@cloudpilot.io",
    title: "VP Engineering",
    seniority: "vp",
    department: "Engineering",
    persona: "Technical Buyer",
    fit_score: 77,
    warmth_score: 68,
    engagement_score: 63,
  },
  {
    id: "con-23",
    account_id: "acc-15",
    name: "Dmitri Volkov",
    email: "dmitri@cloudpilot.io",
    title: "CTO",
    seniority: "c_suite",
    department: "Engineering",
    persona: "Technical Buyer",
    fit_score: 74,
    warmth_score: 61,
    engagement_score: 55,
  },
  // HireFlow (acc-16)
  {
    id: "con-24",
    account_id: "acc-16",
    name: "Ama Asante",
    email: "ama@hireflow.ai",
    title: "CEO",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 82,
    warmth_score: 60,
    engagement_score: 55,
  },
  {
    id: "con-25",
    account_id: "acc-16",
    name: "Tyler Mason",
    email: "tyler@hireflow.ai",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 80,
    warmth_score: 56,
    engagement_score: 50,
  },
  // InsightHQ (acc-17)
  {
    id: "con-26",
    account_id: "acc-17",
    name: "Aria Takahashi",
    email: "aria@insighthq.io",
    title: "Head of Sales",
    seniority: "director",
    department: "Sales",
    persona: "Sales Manager",
    fit_score: 86,
    warmth_score: 74,
    engagement_score: 70,
  },
  {
    id: "con-27",
    account_id: "acc-17",
    name: "Ben Okoro",
    email: "ben@insighthq.io",
    title: "CRO",
    seniority: "c_suite",
    department: "Revenue",
    persona: "Revenue Leader",
    fit_score: 89,
    warmth_score: 80,
    engagement_score: 76,
  },
  {
    id: "con-28",
    account_id: "acc-17",
    name: "Chloe Dubois",
    email: "chloe@insighthq.io",
    title: "VP Product",
    seniority: "vp",
    department: "Product",
    persona: "Product Leader",
    fit_score: 78,
    warmth_score: 65,
    engagement_score: 58,
  },
  // PayStream (acc-18)
  {
    id: "con-29",
    account_id: "acc-18",
    name: "Alex Fernandez",
    email: "alex@paystream.io",
    title: "CEO",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 79,
    warmth_score: 63,
    engagement_score: 57,
  },
  {
    id: "con-30",
    account_id: "acc-18",
    name: "Ingrid Johansson",
    email: "ingrid@paystream.io",
    title: "Head of Partnerships",
    seniority: "director",
    department: "Partnerships",
    persona: "Partnership Buyer",
    fit_score: 76,
    warmth_score: 58,
    engagement_score: 52,
  },
  // TrustGraph (acc-19)
  {
    id: "con-31",
    account_id: "acc-19",
    name: "Noah Patel",
    email: "noah@trustgraph.ai",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 75,
    warmth_score: 57,
    engagement_score: 51,
  },
  {
    id: "con-32",
    account_id: "acc-19",
    name: "Sofia Espinoza",
    email: "sofia@trustgraph.ai",
    title: "CRO",
    seniority: "c_suite",
    department: "Revenue",
    persona: "Revenue Leader",
    fit_score: 72,
    warmth_score: 54,
    engagement_score: 48,
  },
  // FluxOps (acc-20)
  {
    id: "con-33",
    account_id: "acc-20",
    name: "Luca Romano",
    email: "luca@fluxops.io",
    title: "CEO & Founder",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 91,
    warmth_score: 82,
    engagement_score: 78,
  },
  {
    id: "con-34",
    account_id: "acc-20",
    name: "Hana Park",
    email: "hana@fluxops.io",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 88,
    warmth_score: 76,
    engagement_score: 70,
  },
  {
    id: "con-35",
    account_id: "acc-20",
    name: "Raj Kapoor",
    email: "raj@fluxops.io",
    title: "Head of RevOps",
    seniority: "director",
    department: "RevOps",
    persona: "RevOps Builder",
    fit_score: 86,
    warmth_score: 71,
    engagement_score: 65,
  },
  // DataRovers (acc-21)
  {
    id: "con-36",
    account_id: "acc-21",
    name: "Mei Zhang",
    email: "mei@datarovers.com",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 89,
    warmth_score: 67,
    engagement_score: 62,
  },
  {
    id: "con-37",
    account_id: "acc-21",
    name: "Kwame Owusu",
    email: "kwame@datarovers.com",
    title: "CEO",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 86,
    warmth_score: 62,
    engagement_score: 57,
  },
  // TeamSync (acc-22)
  {
    id: "con-38",
    account_id: "acc-22",
    name: "Sara Liu",
    email: "sara@teamsync.io",
    title: "CRO",
    seniority: "c_suite",
    department: "Revenue",
    persona: "Revenue Leader",
    fit_score: 84,
    warmth_score: 73,
    engagement_score: 69,
  },
  {
    id: "con-39",
    account_id: "acc-22",
    name: "Oliver Banks",
    email: "oliver@teamsync.io",
    title: "Director of Sales",
    seniority: "director",
    department: "Sales",
    persona: "Sales Manager",
    fit_score: 81,
    warmth_score: 68,
    engagement_score: 63,
  },
  // RevenueIQ (acc-23)
  {
    id: "con-40",
    account_id: "acc-23",
    name: "Amara Diallo",
    email: "amara@revenueiq.ai",
    title: "CEO & Co-Founder",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 95,
    warmth_score: 76,
    engagement_score: 72,
  },
  {
    id: "con-41",
    account_id: "acc-23",
    name: "Derek Walsh",
    email: "derek@revenueiq.ai",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 92,
    warmth_score: 72,
    engagement_score: 68,
  },
  {
    id: "con-42",
    account_id: "acc-23",
    name: "Yuki Tanaka",
    email: "yuki@revenueiq.ai",
    title: "Head of RevOps",
    seniority: "director",
    department: "RevOps",
    persona: "RevOps Builder",
    fit_score: 90,
    warmth_score: 68,
    engagement_score: 62,
  },
  // LeadMesh (acc-24)
  {
    id: "con-43",
    account_id: "acc-24",
    name: "Penelope Cruz",
    email: "penelope@leadmesh.io",
    title: "VP of Growth",
    seniority: "vp",
    department: "Growth",
    persona: "Growth Leader",
    fit_score: 86,
    warmth_score: 65,
    engagement_score: 60,
  },
  {
    id: "con-44",
    account_id: "acc-24",
    name: "Tobias Lindqvist",
    email: "tobias@leadmesh.io",
    title: "CEO",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder/CEO",
    fit_score: 83,
    warmth_score: 61,
    engagement_score: 55,
  },
  // GrowthEngine (acc-25)
  {
    id: "con-45",
    account_id: "acc-25",
    name: "Zoe Williams",
    email: "zoe@growthengine.ai",
    title: "CRO",
    seniority: "c_suite",
    department: "Revenue",
    persona: "Revenue Leader",
    fit_score: 94,
    warmth_score: 71,
    engagement_score: 67,
  },
  {
    id: "con-46",
    account_id: "acc-25",
    name: "Marcus Oyelaran",
    email: "marcus.o@growthengine.ai",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 91,
    warmth_score: 67,
    engagement_score: 63,
  },
  {
    id: "con-47",
    account_id: "acc-25",
    name: "Priya Kumar",
    email: "priya.k@growthengine.ai",
    title: "Director of Demand Gen",
    seniority: "director",
    department: "Marketing",
    persona: "Marketing Leader",
    fit_score: 87,
    warmth_score: 62,
    engagement_score: 58,
  },
];

// ─── Audit Log ─────────────────────────────────────────────────────────────

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: "al-1",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "workspace.created",
    entity_type: "workspace",
    entity_id: "ws-1",
    entity_name: "WarmPath",
    created_at: daysAgo(110),
  },
  {
    id: "al-2",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "user.login",
    metadata: { method: "demo" },
    created_at: daysAgo(5),
  },
  {
    id: "al-3",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "onboarding.completed",
    created_at: daysAgo(108),
  },
  {
    id: "al-4",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "integration.connected",
    entity_type: "integration",
    entity_id: "gmail",
    entity_name: "Gmail",
    metadata: { connections_mapped: 847 },
    created_at: daysAgo(107),
  },
  {
    id: "al-5",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "integration.connected",
    entity_type: "integration",
    entity_id: "linkedin",
    entity_name: "LinkedIn",
    metadata: { connections_mapped: 1253 },
    created_at: daysAgo(107),
  },
  {
    id: "al-6",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "kb.item_added",
    entity_type: "kb_item",
    entity_id: "kb-1",
    entity_name: "WarmPath Product Overview",
    created_at: daysAgo(90),
  },
  {
    id: "al-7",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "kb.item_added",
    entity_type: "kb_item",
    entity_id: "kb-2",
    entity_name: "Core Value Proposition",
    created_at: daysAgo(88),
  },
  {
    id: "al-8",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "kb.item_added",
    entity_type: "kb_item",
    entity_id: "kb-8",
    entity_name: "Approved Claims",
    created_at: daysAgo(55),
  },
  {
    id: "al-9",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "kb.item_approved",
    entity_type: "kb_item",
    entity_id: "kb-7",
    entity_name: "Case Study SeriesAI",
    metadata: { previous_status: false, new_status: true },
    created_at: daysAgo(59),
  },
  {
    id: "al-10",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "campaign.launched",
    entity_type: "campaign",
    entity_id: "camp-1",
    entity_name: "Series A Funded Companies GTM Scaling",
    metadata: { total_prospects: 24 },
    created_at: daysAgo(30),
  },
  {
    id: "al-11",
    workspace_id: "ws-1",
    actor_user_id: "tm-2",
    actor_name: "Sarah Chen",
    action: "campaign.launched",
    entity_type: "campaign",
    entity_id: "camp-2",
    entity_name: "Hiring Signal SDR & RevOps Roles",
    metadata: { total_prospects: 31 },
    created_at: daysAgo(20),
  },
  {
    id: "al-12",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "message.generated",
    entity_type: "message",
    entity_id: "msg-1",
    entity_name: "Intro request → Priya @ Acme AI",
    metadata: { channel: "warm_intro", confidence: 0.91 },
    created_at: ago(6),
  },
  {
    id: "al-13",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "message.generated",
    entity_type: "message",
    entity_id: "msg-2",
    entity_name: "Email → Elena @ Finpilot",
    metadata: { channel: "email", confidence: 0.87 },
    created_at: ago(5),
  },
  {
    id: "al-14",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "message.approved",
    entity_type: "message",
    entity_id: "msg-5",
    entity_name: "Email → Rachel @ BrightOps",
    metadata: { channel: "email", edit_made: false },
    created_at: ago(3),
  },
  {
    id: "al-15",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "message.generated",
    entity_type: "message",
    entity_id: "msg-3",
    entity_name: "Email → David @ RevScale",
    metadata: { channel: "email", confidence: 0.88 },
    created_at: ago(4),
  },
  {
    id: "al-16",
    workspace_id: "ws-1",
    actor_user_id: "tm-3",
    actor_name: "Rohan Mehta",
    action: "message.generated",
    entity_type: "message",
    entity_id: "msg-4",
    entity_name: "Email → Liam @ CloudNest",
    metadata: { channel: "email", confidence: 0.94 },
    created_at: ago(5),
  },
  {
    id: "al-17",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "kb.item_updated",
    entity_type: "kb_item",
    entity_id: "kb-4",
    entity_name: "Ideal Customer Profile",
    metadata: { fields_changed: "content,tags" },
    created_at: daysAgo(10),
  },
  {
    id: "al-18",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "settings.updated",
    entity_type: "settings",
    metadata: { section: "ai_mode", new_value: "mock" },
    created_at: daysAgo(3),
  },
  {
    id: "al-19",
    workspace_id: "ws-1",
    actor_user_id: "tm-2",
    actor_name: "Sarah Chen",
    action: "message.regenerated",
    entity_type: "message",
    entity_id: "msg-2",
    entity_name: "Email → Elena @ Finpilot",
    metadata: { reason: "too_long" },
    created_at: ago(4),
  },
  {
    id: "al-20",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "plan.upgraded",
    entity_type: "subscription",
    metadata: { from_plan: "free", to_plan: "growth", amount: 149 },
    created_at: daysAgo(95),
  },
  {
    id: "al-21",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "user.login",
    metadata: { method: "demo" },
    created_at: ago(2),
  },
  {
    id: "al-22",
    workspace_id: "ws-1",
    actor_user_id: "tm-4",
    actor_name: "Maya Iyer",
    action: "integration.connected",
    entity_type: "integration",
    entity_id: "hubspot",
    entity_name: "HubSpot",
    metadata: { contacts_synced: 234 },
    created_at: daysAgo(55),
  },
  {
    id: "al-23",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "kb.item_added",
    entity_type: "kb_item",
    entity_id: "kb-9",
    entity_name: "Banned Claims",
    created_at: daysAgo(50),
  },
  {
    id: "al-24",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "test.scenario_run",
    entity_type: "test_scenario",
    entity_id: "ts-8",
    entity_name: "End-to-End Demo",
    metadata: { status: "passed", duration_ms: 12400 },
    created_at: daysAgo(1),
  },
  {
    id: "al-25",
    workspace_id: "ws-1",
    actor_user_id: "user-1",
    actor_name: "Adhik Agarwal",
    action: "message.rejected",
    entity_type: "message",
    entity_id: "msg-3",
    entity_name: "Email → David @ RevScale",
    metadata: { reason: "needs_stronger_hook" },
    created_at: ago(2),
  },
];

// ─── AI Usage Logs ─────────────────────────────────────────────────────────

export const DEMO_AI_USAGE: AIUsageLog[] = [
  {
    id: "au-1",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "generate_message",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(6),
  },
  {
    id: "au-2",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "generate_message",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(5),
  },
  {
    id: "au-3",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "generate_message",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(4),
  },
  {
    id: "au-4",
    workspace_id: "ws-1",
    user_id: "tm-3",
    action_type: "generate_message",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(5),
  },
  {
    id: "au-5",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "generate_message",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(3),
  },
  {
    id: "au-6",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "analyze_risk",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(3),
  },
  {
    id: "au-7",
    workspace_id: "ws-1",
    user_id: "tm-2",
    action_type: "analyze_risk",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    cache_hit: true,
    created_at: ago(4),
  },
  {
    id: "au-8",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "recommend_actions",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(6),
  },
  {
    id: "au-9",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "recommend_actions",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "cached",
    cache_hit: true,
    created_at: ago(2),
  },
  {
    id: "au-10",
    workspace_id: "ws-1",
    user_id: "user-1",
    action_type: "kb_retrieval",
    provider: "mock",
    model: "warmpath-mock-v1",
    input_tokens: 0,
    output_tokens: 0,
    estimated_cost: 0,
    status: "success",
    created_at: ago(1),
  },
];

// ─── User Test Scenarios ───────────────────────────────────────────────────

export const DEMO_TEST_SCENARIOS: UserTestScenario[] = [
  {
    id: "ts-1",
    name: "Founder Onboarding",
    persona: "New Founder",
    description:
      "First-time user completing full onboarding: workspace → ICP → team → integrations → first warm leads.",
    status: "passed",
    last_run_at: daysAgo(2),
    duration_ms: 8200,
    issues_found: [],
    steps: [
      {
        id: "ts-1-1",
        description: "Land on marketing page, click 'Get started'",
        status: "passed",
        result: "Landing page loads in <1s, CTA visible immediately",
      },
      {
        id: "ts-1-2",
        description: "Enter demo mode from login page",
        status: "passed",
        result: "Demo login succeeds, redirects to /dashboard",
      },
      {
        id: "ts-1-3",
        description: "Navigate to onboarding wizard",
        status: "passed",
        result: "8-step wizard loads correctly",
      },
      {
        id: "ts-1-4",
        description: "Complete company + ICP setup",
        status: "passed",
        result: "All form inputs save to store",
      },
      {
        id: "ts-1-5",
        description: "Connect LinkedIn (simulated)",
        status: "passed",
        result: "Connection simulated, 847 connections mapped",
      },
      {
        id: "ts-1-6",
        description: "Finish onboarding → see dashboard",
        status: "passed",
        result: "Dashboard loads with demo data populated",
      },
    ],
  },
  {
    id: "ts-2",
    name: "Sales Rep Approvals",
    persona: "Sales Rep",
    description:
      "Sales rep reviewing, editing, and approving AI-generated messages in the approval queue.",
    status: "passed",
    last_run_at: daysAgo(1),
    duration_ms: 5100,
    issues_found: [],
    steps: [
      {
        id: "ts-2-1",
        description: "Open approval queue from sidebar",
        status: "passed",
        result: "Queue loads with 4 pending messages",
      },
      {
        id: "ts-2-2",
        description: "Review first message (warm intro request)",
        status: "passed",
        result: "KB-grounded claims visible, warm path shown",
      },
      {
        id: "ts-2-3",
        description: "Approve message using 'A' keyboard shortcut",
        status: "passed",
        result: "Status changes to 'approved', toast notification fires",
      },
      {
        id: "ts-2-4",
        description: "Edit second message body",
        status: "passed",
        result: "Edit mode activates, textarea editable",
      },
      {
        id: "ts-2-5",
        description: "Save edit and approve",
        status: "passed",
        result: "Edited body saved, status → approved",
      },
      {
        id: "ts-2-6",
        description: "Reject one message with feedback",
        status: "passed",
        result: "Status → rejected, reason logged in audit",
      },
    ],
  },
  {
    id: "ts-3",
    name: "Knowledge Base Setup",
    persona: "Admin / Founder",
    description:
      "Adding, editing, and approving KB items that the AI will use for message grounding.",
    status: "passed",
    last_run_at: daysAgo(1),
    duration_ms: 4400,
    issues_found: [],
    steps: [
      {
        id: "ts-3-1",
        description: "Open Knowledge Base from sidebar",
        status: "passed",
        result: "KB page loads with 12 demo items",
      },
      {
        id: "ts-3-2",
        description: "Check AI readiness score",
        status: "passed",
        result: "Score shows 75% (9/12 items approved)",
      },
      {
        id: "ts-3-3",
        description: "Add new KB item (product update)",
        status: "passed",
        result: "Item saved to store, appears in list",
      },
      {
        id: "ts-3-4",
        description: "Toggle 'Approved for AI' on new item",
        status: "passed",
        result: "Toggle updates, readiness score rises",
      },
      {
        id: "ts-3-5",
        description: "Edit existing item content",
        status: "passed",
        result: "Edit saves, updated_at timestamp refreshes",
      },
      {
        id: "ts-3-6",
        description: "Verify KB readiness score updated",
        status: "passed",
        result: "Score correctly reflects approved count",
      },
    ],
  },
  {
    id: "ts-4",
    name: "Campaign Creation",
    persona: "Growth Lead",
    description: "Creating and launching a new outbound campaign with multi-step sequence.",
    status: "partial",
    last_run_at: daysAgo(1),
    duration_ms: 3800,
    issues_found: ["Campaign builder UI needs 'Add step' functionality"],
    steps: [
      {
        id: "ts-4-1",
        description: "Open Campaigns page",
        status: "passed",
        result: "3 demo campaigns load",
      },
      {
        id: "ts-4-2",
        description: "Click 'New campaign'",
        status: "passed",
        result: "Toast shows 'Campaign builder coming soon'",
      },
      {
        id: "ts-4-3",
        description: "View existing campaign detail",
        status: "passed",
        result: "Campaign detail page loads with steps, stats",
      },
      {
        id: "ts-4-4",
        description: "Launch draft campaign",
        status: "passed",
        result: "Toast fires 'Campaign launched!'",
      },
      {
        id: "ts-4-5",
        description: "Create campaign from demo lab",
        status: "failed",
        result: "Campaign builder not yet implemented toast only",
      },
    ],
  },
  {
    id: "ts-5",
    name: "Free Plan Limit Enforcement",
    persona: "Free Plan User",
    description:
      "Verifying that free plan users are gated when they exceed account/message limits.",
    status: "passed",
    last_run_at: daysAgo(3),
    duration_ms: 2100,
    issues_found: [],
    steps: [
      {
        id: "ts-5-1",
        description: "Open Billing page",
        status: "passed",
        result: "Current plan shown correctly",
      },
      {
        id: "ts-5-2",
        description: "Usage meters display correctly",
        status: "passed",
        result: "Accounts: 10/5 (over), Messages: 5/25",
      },
      {
        id: "ts-5-3",
        description: "Upgrade button triggers Stripe demo",
        status: "passed",
        result: "Toast: 'Stripe checkout would open here'",
      },
      {
        id: "ts-5-4",
        description: "Plan comparison cards visible",
        status: "passed",
        result: "All 3 plans render with correct features",
      },
    ],
  },
  {
    id: "ts-6",
    name: "AI Risk Detection",
    persona: "Sales Rep",
    description: "Checking that message risk flags are surfaced and suggested fixes are shown.",
    status: "passed",
    last_run_at: daysAgo(1),
    duration_ms: 3200,
    issues_found: [],
    steps: [
      {
        id: "ts-6-1",
        description: "Open approval queue message",
        status: "passed",
        result: "Message card renders with risk panel",
      },
      {
        id: "ts-6-2",
        description: "Verify KB-grounded facts shown",
        status: "passed",
        result: "2 verified facts with source badges visible",
      },
      {
        id: "ts-6-3",
        description: "Regenerate message with new tone",
        status: "passed",
        result: "Regenerate fires, new confidence score shown",
      },
      {
        id: "ts-6-4",
        description: "Verify risk flags if present",
        status: "passed",
        result: "Risk type, severity, suggested fix visible",
      },
    ],
  },
  {
    id: "ts-7",
    name: "Integration Health Check",
    persona: "Admin",
    description: "Verifying integrations page shows accurate connection states and reconnect flow.",
    status: "passed",
    last_run_at: daysAgo(2),
    duration_ms: 2600,
    issues_found: [],
    steps: [
      {
        id: "ts-7-1",
        description: "Open Integrations page",
        status: "passed",
        result: "8 integrations shown with correct status badges",
      },
      {
        id: "ts-7-2",
        description: "Connect a disconnected integration",
        status: "passed",
        result: "Status toggles to 'Connected', toast fires",
      },
      {
        id: "ts-7-3",
        description: "Reconnect errored Slack integration",
        status: "passed",
        result: "Status changes to 'Connected'",
      },
      {
        id: "ts-7-4",
        description: "Disconnect an active integration",
        status: "passed",
        result: "Status changes to 'Not connected'",
      },
    ],
  },
  {
    id: "ts-8",
    name: "End-to-End Full Demo",
    persona: "Investor / Prospect",
    description:
      "Complete product walkthrough: onboarding → KB → warm leads → approval → campaign → dashboard.",
    status: "passed",
    last_run_at: daysAgo(1),
    duration_ms: 12400,
    issues_found: [],
    steps: [
      {
        id: "ts-8-1",
        description: "Land on marketing page",
        status: "passed",
        result: "Page loads, warm path USP visible in 3 seconds",
      },
      {
        id: "ts-8-2",
        description: "Enter demo mode",
        status: "passed",
        result: "Auth succeeds, workspace loaded",
      },
      {
        id: "ts-8-3",
        description: "Review dashboard command center",
        status: "passed",
        result: "Today's priorities, signals, approvals visible",
      },
      {
        id: "ts-8-4",
        description: "Open Knowledge Base",
        status: "passed",
        result: "AI readiness score and 12 items visible",
      },
      {
        id: "ts-8-5",
        description: "Open Warm Leads",
        status: "passed",
        result: "Accounts ranked by warm-path score",
      },
      {
        id: "ts-8-6",
        description: "Review first warm lead detail",
        status: "passed",
        result: "Signal + warm path + opportunity score visible",
      },
      {
        id: "ts-8-7",
        description: "Open Approval Queue",
        status: "passed",
        result: "4 pending messages, KB grounding shown",
      },
      {
        id: "ts-8-8",
        description: "Approve a message",
        status: "passed",
        result: "Status → approved, audit log updated",
      },
      {
        id: "ts-8-9",
        description: "Open Signals feed",
        status: "passed",
        result: "8 signals, urgency-sorted, all actionable",
      },
      {
        id: "ts-8-10",
        description: "Open Relationship Graph",
        status: "passed",
        result: "Interactive graph renders with warm paths",
      },
      {
        id: "ts-8-11",
        description: "Open Campaign detail",
        status: "passed",
        result: "38.9% reply rate visible, steps shown",
      },
      {
        id: "ts-8-12",
        description: "Open Billing → verify plan gating",
        status: "passed",
        result: "Growth plan, usage meters correct",
      },
      {
        id: "ts-8-13",
        description: "Open AI Usage page",
        status: "passed",
        result: "Mock mode, $0 cost, 10 logs visible",
      },
      {
        id: "ts-8-14",
        description: "Open Audit Log",
        status: "passed",
        result: "25 events, timeline format, filters work",
      },
      {
        id: "ts-8-15",
        description: "Return to dashboard full loop",
        status: "passed",
        result: "All state consistent, no broken links",
      },
    ],
  },
];
