import type {
  Account,
  Campaign,
  Contact,
  GeneratedMessage,
  Interaction,
  NextBestAction,
  RelationshipEdge,
  Signal,
  Subscription,
  TeamMember,
  User,
  WarmPath,
} from "@/types";

export const DEMO_USER: User = {
  id: "user-1",
  name: "Adhik Agarwal",
  email: "adhik@warmpath.ai",
  company_name: "WarmPath",
  role: "Founder & CEO",
  plan: "growth",
  onboarding_completed: true,
  created_at: "2026-01-15T09:00:00Z",
};

export const DEMO_TEAM: TeamMember[] = [
  {
    id: "tm-1",
    user_id: "user-1",
    name: "Adhik Agarwal",
    email: "adhik@warmpath.ai",
    title: "Founder & CEO",
    connected_sources: ["gmail", "linkedin"],
    relationship_score: 95,
  },
  {
    id: "tm-2",
    user_id: "user-1",
    name: "Sarah Chen",
    email: "sarah@warmpath.ai",
    title: "Advisor Ex-Salesforce",
    connected_sources: ["gmail", "linkedin", "salesforce"],
    relationship_score: 88,
  },
  {
    id: "tm-3",
    user_id: "user-1",
    name: "Rohan Mehta",
    email: "rohan@warmpath.ai",
    title: "Co-Founder",
    connected_sources: ["gmail", "linkedin"],
    relationship_score: 82,
  },
  {
    id: "tm-4",
    user_id: "user-1",
    name: "Maya Iyer",
    email: "maya@warmpath.ai",
    title: "Sales Consultant",
    connected_sources: ["outlook", "linkedin", "hubspot"],
    relationship_score: 76,
  },
];

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    name: "Acme AI",
    domain: "acme.ai",
    industry: "AI / SaaS",
    employee_count: 120,
    location: "San Francisco, CA",
    description: "AI-powered revenue operations platform for mid-market B2B companies.",
    stage: "engaged",
    fit_score: 94,
    intent_score: 91,
    warmth_score: 88,
    opportunity_score: 92,
    created_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "acc-2",
    name: "Finpilot",
    domain: "finpilot.com",
    industry: "FinTech",
    employee_count: 85,
    location: "New York, NY",
    description: "AI copilot for financial analysts automating research and reporting.",
    stage: "meeting",
    fit_score: 91,
    intent_score: 88,
    warmth_score: 72,
    opportunity_score: 86,
    created_at: "2026-03-28T10:00:00Z",
  },
  {
    id: "acc-3",
    name: "RevScale",
    domain: "revscale.io",
    industry: "Sales Tech",
    employee_count: 210,
    location: "Austin, TX",
    description: "Revenue acceleration platform for Series A–C SaaS companies.",
    stage: "prospect",
    fit_score: 89,
    intent_score: 95,
    warmth_score: 65,
    opportunity_score: 84,
    created_at: "2026-04-10T10:00:00Z",
  },
  {
    id: "acc-4",
    name: "CloudNest",
    domain: "cloudnest.dev",
    industry: "DevTools",
    employee_count: 55,
    location: "Seattle, WA",
    description: "Cloud infrastructure tooling for developer-led organizations.",
    stage: "prospect",
    fit_score: 82,
    intent_score: 79,
    warmth_score: 91,
    opportunity_score: 84,
    created_at: "2026-04-05T10:00:00Z",
  },
  {
    id: "acc-5",
    name: "Northstar Analytics",
    domain: "northstar.io",
    industry: "Analytics / BI",
    employee_count: 145,
    location: "Chicago, IL",
    description: "Next-gen business intelligence for data teams at growth-stage companies.",
    stage: "prospect",
    fit_score: 87,
    intent_score: 73,
    warmth_score: 78,
    opportunity_score: 80,
    created_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "acc-6",
    name: "LedgerFlow",
    domain: "ledgerflow.com",
    industry: "FinTech",
    employee_count: 68,
    location: "Boston, MA",
    description: "Automated accounting workflows for finance teams at startups.",
    stage: "engaged",
    fit_score: 85,
    intent_score: 82,
    warmth_score: 69,
    opportunity_score: 79,
    created_at: "2026-04-08T10:00:00Z",
  },
  {
    id: "acc-7",
    name: "BrightOps",
    domain: "brightops.com",
    industry: "RevOps / GTM",
    employee_count: 95,
    location: "Denver, CO",
    description: "RevOps automation platform integrates CRM, data, and go-to-market execution.",
    stage: "prospect",
    fit_score: 96,
    intent_score: 88,
    warmth_score: 74,
    opportunity_score: 87,
    created_at: "2026-04-12T10:00:00Z",
  },
  {
    id: "acc-8",
    name: "TalentGrid",
    domain: "talentgrid.ai",
    industry: "HR Tech",
    employee_count: 175,
    location: "San Francisco, CA",
    description: "AI-driven talent intelligence and hiring automation platform.",
    stage: "prospect",
    fit_score: 78,
    intent_score: 86,
    warmth_score: 83,
    opportunity_score: 82,
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "acc-9",
    name: "VectorPay",
    domain: "vectorpay.io",
    industry: "Payments",
    employee_count: 130,
    location: "New York, NY",
    description: "B2B payments infrastructure for SaaS companies and marketplaces.",
    stage: "prospect",
    fit_score: 80,
    intent_score: 77,
    warmth_score: 62,
    opportunity_score: 74,
    created_at: "2026-04-02T10:00:00Z",
  },
  {
    id: "acc-10",
    name: "OrbitCRM",
    domain: "orbitcrm.com",
    industry: "CRM / Sales",
    employee_count: 320,
    location: "Miami, FL",
    description: "Modern CRM built for high-velocity sales teams pipeline-first, signal-aware.",
    stage: "proposal",
    fit_score: 92,
    intent_score: 84,
    warmth_score: 70,
    opportunity_score: 83,
    created_at: "2026-02-28T10:00:00Z",
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "con-1",
    account_id: "acc-1",
    name: "Priya Sharma",
    email: "priya@acme.ai",
    title: "VP of Sales",
    linkedin_url: "https://linkedin.com/in/priyasharma",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 95,
    warmth_score: 88,
    engagement_score: 76,
  },
  {
    id: "con-2",
    account_id: "acc-1",
    name: "Marcus Williams",
    email: "marcus@acme.ai",
    title: "Head of RevOps",
    seniority: "director",
    department: "RevOps",
    persona: "RevOps Builder",
    fit_score: 90,
    warmth_score: 72,
    engagement_score: 64,
  },
  {
    id: "con-3",
    account_id: "acc-2",
    name: "Elena Rodriguez",
    email: "elena@finpilot.com",
    title: "CEO",
    linkedin_url: "https://linkedin.com/in/elenarodriguez",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder / CEO",
    fit_score: 91,
    warmth_score: 72,
    engagement_score: 81,
  },
  {
    id: "con-4",
    account_id: "acc-2",
    name: "James Park",
    email: "james@finpilot.com",
    title: "VP of Growth",
    seniority: "vp",
    department: "Growth",
    persona: "Growth Leader",
    fit_score: 88,
    warmth_score: 65,
    engagement_score: 58,
  },
  {
    id: "con-5",
    account_id: "acc-3",
    name: "David Kim",
    email: "david@revscale.io",
    title: "CRO",
    seniority: "c_suite",
    department: "Revenue",
    persona: "Revenue Leader",
    fit_score: 92,
    warmth_score: 65,
    engagement_score: 72,
  },
  {
    id: "con-6",
    account_id: "acc-3",
    name: "Samantha Torres",
    email: "sam@revscale.io",
    title: "Director of Sales",
    seniority: "director",
    department: "Sales",
    persona: "Sales Manager",
    fit_score: 88,
    warmth_score: 71,
    engagement_score: 60,
  },
  {
    id: "con-7",
    account_id: "acc-4",
    name: "Liam Chen",
    email: "liam@cloudnest.dev",
    title: "CTO",
    seniority: "c_suite",
    department: "Engineering",
    persona: "Technical Buyer",
    fit_score: 82,
    warmth_score: 91,
    engagement_score: 88,
  },
  {
    id: "con-8",
    account_id: "acc-5",
    name: "Aisha Patel",
    email: "aisha@northstar.io",
    title: "Head of Data",
    seniority: "director",
    department: "Data",
    persona: "Data Leader",
    fit_score: 87,
    warmth_score: 78,
    engagement_score: 70,
  },
  {
    id: "con-9",
    account_id: "acc-6",
    name: "Tom Nakamura",
    email: "tom@ledgerflow.com",
    title: "VP Finance",
    seniority: "vp",
    department: "Finance",
    persona: "Finance Buyer",
    fit_score: 85,
    warmth_score: 69,
    engagement_score: 55,
  },
  {
    id: "con-10",
    account_id: "acc-7",
    name: "Rachel Green",
    email: "rachel@brightops.com",
    title: "CEO",
    seniority: "c_suite",
    department: "Executive",
    persona: "Founder / CEO",
    fit_score: 96,
    warmth_score: 74,
    engagement_score: 67,
  },
  {
    id: "con-11",
    account_id: "acc-8",
    name: "Kevin Zhang",
    email: "kevin@talentgrid.ai",
    title: "VP Sales",
    seniority: "vp",
    department: "Sales",
    persona: "Revenue Leader",
    fit_score: 78,
    warmth_score: 83,
    engagement_score: 79,
  },
  {
    id: "con-12",
    account_id: "acc-10",
    name: "Nina Okoye",
    email: "nina@orbitcrm.com",
    title: "Head of Partnerships",
    seniority: "director",
    department: "Partnerships",
    persona: "Partnership Buyer",
    fit_score: 92,
    warmth_score: 70,
    engagement_score: 63,
  },
];

export const DEMO_SIGNALS: Signal[] = [
  {
    id: "sig-1",
    account_id: "acc-1",
    contact_id: "con-1",
    type: "job_posting",
    title: "Acme AI is hiring 4 SDRs and a RevOps Manager",
    description:
      "Acme AI posted 4 SDR roles and a RevOps Manager on LinkedIn in the last 7 days. Strong signal they're scaling outbound and need GTM tooling.",
    source: "LinkedIn Jobs",
    detected_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    urgency_score: 92,
    confidence_score: 95,
    recommended_action: "Reach out to VP Sales about outbound scaling challenges",
  },
  {
    id: "sig-2",
    account_id: "acc-2",
    type: "pricing_page_visit",
    title: "Finpilot visited the pricing page twice this week",
    description:
      "finpilot.com IP visited your pricing page on Mon and Wed. They spent 4 min on the Growth plan details.",
    source: "Website Tracking",
    detected_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    urgency_score: 88,
    confidence_score: 85,
    recommended_action: "Follow up with a timely, relevant message referencing their interest",
  },
  {
    id: "sig-3",
    account_id: "acc-3",
    type: "funding",
    title: "RevScale raised $12M Series A",
    description:
      "RevScale announced a $12M Series A led by Bessemer. They plan to 3x their GTM team in the next 6 months.",
    source: "TechCrunch",
    source_url: "https://techcrunch.com",
    detected_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    urgency_score: 95,
    confidence_score: 99,
    recommended_action: "Strike now funding means budget and urgency to scale",
  },
  {
    id: "sig-4",
    account_id: "acc-4",
    type: "linkedin_post",
    title: "CloudNest CTO posted about scaling their outbound motion",
    description:
      'Liam Chen posted: "Building outbound from 0 to 1 is our biggest challenge this quarter. Open to conversations with founders who\'ve done this."',
    source: "LinkedIn",
    detected_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    urgency_score: 91,
    confidence_score: 97,
    recommended_action: "Respond to the post or reach out directly they're actively looking",
  },
  {
    id: "sig-5",
    account_id: "acc-6",
    type: "tech_stack_change",
    title: "LedgerFlow added HubSpot to their tech stack",
    description:
      "LedgerFlow's job postings now require HubSpot experience. They recently adopted HubSpot CRM, suggesting active GTM buildout.",
    source: "BuiltWith / Job Signals",
    detected_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    urgency_score: 78,
    confidence_score: 82,
    recommended_action: "HubSpot adoption = active GTM investment. Perfect timing for outreach.",
  },
  {
    id: "sig-6",
    account_id: "acc-8",
    contact_id: "con-11",
    type: "champion_job_change",
    title: "Kevin Zhang moved from Northstar to TalentGrid",
    description:
      "Kevin Zhang, formerly Head of Sales at Northstar Analytics (where you have a past relationship), just joined TalentGrid as VP Sales.",
    source: "LinkedIn",
    detected_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    urgency_score: 86,
    confidence_score: 98,
    recommended_action: "Champion moved to new account warm reach out immediately",
  },
  {
    id: "sig-7",
    account_id: "acc-7",
    contact_id: "con-10",
    type: "job_posting",
    title: "BrightOps hiring 3 Account Executives and a Sales Engineer",
    description:
      "BrightOps posted 3 AE roles (Mid-Market focus) and a Sales Engineer. Strong signal they're building an outbound sales motion.",
    source: "LinkedIn Jobs",
    detected_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    urgency_score: 89,
    confidence_score: 92,
    recommended_action: "CEO is building a sales team she needs GTM tooling right now",
  },
  {
    id: "sig-8",
    account_id: "acc-10",
    type: "g2_review",
    title: "OrbitCRM reviewing AI sales tools on G2",
    description:
      "OrbitCRM team left reviews on 3 competing AI SDR products on G2 in the last 2 weeks. Actively evaluating the space.",
    source: "G2 Intent",
    detected_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    urgency_score: 83,
    confidence_score: 88,
    recommended_action: "They're actively comparing reach out with a differentiated angle",
  },
];

export const DEMO_RELATIONSHIP_EDGES: RelationshipEdge[] = [
  {
    id: "re-1",
    from_type: "team_member",
    from_id: "tm-2",
    from_name: "Sarah Chen",
    to_type: "contact",
    to_id: "con-1",
    to_name: "Priya Sharma",
    relationship_type: "linkedin_connection",
    strength_score: 85,
    evidence: "Connected on LinkedIn for 3 years. Interacted on 4 posts.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-2",
    from_type: "team_member",
    from_id: "tm-3",
    from_name: "Rohan Mehta",
    to_type: "contact",
    to_id: "con-3",
    to_name: "Elena Rodriguez",
    relationship_type: "email_history",
    strength_score: 78,
    evidence: "Exchanged 6 emails at a Y Combinator event in 2024.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-3",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "contact",
    to_id: "con-7",
    to_name: "Liam Chen",
    relationship_type: "calendar_meeting",
    strength_score: 91,
    evidence: "Met at SaaStr Annual 2025. Follow-up call in Aug 2025.",
    source: "Google Calendar",
    last_interaction_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-4",
    from_type: "team_member",
    from_id: "tm-4",
    from_name: "Maya Iyer",
    to_type: "contact",
    to_id: "con-5",
    to_name: "David Kim",
    relationship_type: "linkedin_connection",
    strength_score: 72,
    evidence: "2nd-degree connection via Andreessen Horowitz network.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-5",
    from_type: "team_member",
    from_id: "tm-2",
    from_name: "Sarah Chen",
    to_type: "contact",
    to_id: "con-8",
    to_name: "Aisha Patel",
    relationship_type: "coworker_connection",
    strength_score: 88,
    evidence: "Worked together at Salesforce Data Cloud 2022–2024.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-6",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "contact",
    to_id: "con-10",
    to_name: "Rachel Green",
    relationship_type: "intro_history",
    strength_score: 82,
    evidence: "Introduced by mutual investor. Had a discovery call in Q1 2026.",
    source: "Email",
    last_interaction_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-7",
    from_type: "team_member",
    from_id: "tm-3",
    from_name: "Rohan Mehta",
    to_type: "contact",
    to_id: "con-11",
    to_name: "Kevin Zhang",
    relationship_type: "email_history",
    strength_score: 75,
    evidence: "Kevin was at Northstar Analytics Rohan had a demo call with him in 2025.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── Team ↔ Team (so graph finds paths through teammates) ─────────────────
  {
    id: "re-8",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "team_member",
    to_id: "tm-2",
    to_name: "Sarah Chen",
    relationship_type: "coworker_connection",
    strength_score: 95,
    evidence: "Advisor relationship since 2024. Weekly syncs.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-9",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "team_member",
    to_id: "tm-3",
    to_name: "Rohan Mehta",
    relationship_type: "coworker_connection",
    strength_score: 93,
    evidence: "Co-founder. Daily contact.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-10",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "team_member",
    to_id: "tm-4",
    to_name: "Maya Iyer",
    relationship_type: "coworker_connection",
    strength_score: 88,
    evidence: "Sales consultant, brought in Jan 2026.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── Direct user connections ───────────────────────────────────────────────
  {
    id: "re-11",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "contact",
    to_id: "con-1",
    to_name: "Priya Sharma",
    relationship_type: "linkedin_connection",
    strength_score: 62,
    evidence: "Connected on LinkedIn after a SaaStr panel. No direct emails.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-12",
    from_type: "user",
    from_id: "user-1",
    from_name: "Adhik Agarwal",
    to_type: "contact",
    to_id: "con-6",
    to_name: "Sophie Anderson",
    relationship_type: "email_history",
    strength_score: 70,
    evidence: "Emailed 3 times about a partnership at TechCrunch Disrupt 2025.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── Contact ↔ Contact (2nd-degree paths) ─────────────────────────────────
  {
    id: "re-13",
    from_type: "contact",
    from_id: "con-1",
    from_name: "Priya Sharma",
    to_type: "contact",
    to_id: "con-2",
    to_name: "Marcus Johnson",
    relationship_type: "coworker_connection",
    strength_score: 82,
    evidence: "Co-workers at Acme AI Priya is VP Sales, Marcus is Head of RevOps.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-14",
    from_type: "contact",
    from_id: "con-1",
    from_name: "Priya Sharma",
    to_type: "contact",
    to_id: "con-4",
    to_name: "James Park",
    relationship_type: "linkedin_connection",
    strength_score: 65,
    evidence: "Former colleagues at Salesforce, connected on LinkedIn 2023.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-15",
    from_type: "contact",
    from_id: "con-5",
    from_name: "David Kim",
    to_type: "contact",
    to_id: "con-9",
    to_name: "Amir Hassan",
    relationship_type: "calendar_meeting",
    strength_score: 74,
    evidence: "Met at YC Demo Day Fall 2024. Had a follow-up coffee.",
    source: "Google Calendar",
    last_interaction_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-16",
    from_type: "contact",
    from_id: "con-7",
    from_name: "Liam Chen",
    to_type: "contact",
    to_id: "con-11",
    to_name: "Kevin Zhang",
    relationship_type: "linkedin_connection",
    strength_score: 58,
    evidence: "Alumni from the same Stanford MBA cohort.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-17",
    from_type: "contact",
    from_id: "con-8",
    from_name: "Aisha Patel",
    to_type: "contact",
    to_id: "con-10",
    to_name: "Rachel Green",
    relationship_type: "coworker_connection",
    strength_score: 80,
    evidence: "Both at HubSpot 2021–2023. Still close professionally.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-18",
    from_type: "contact",
    from_id: "con-3",
    from_name: "Elena Rodriguez",
    to_type: "contact",
    to_id: "con-6",
    to_name: "Sophie Anderson",
    relationship_type: "email_history",
    strength_score: 68,
    evidence: "Collaborated on a joint GTM webinar in Q3 2025.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── 3rd-degree connectors (demonstrates 3-hop paths) ─────────────────────
  {
    id: "re-19",
    from_type: "contact",
    from_id: "con-4",
    from_name: "James Park",
    to_type: "contact",
    to_id: "con-9",
    to_name: "Amir Hassan",
    relationship_type: "intro_history",
    strength_score: 85,
    evidence: "James introduced Amir to a VC in 2024 strong mutual trust.",
    source: "Email",
    last_interaction_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-20",
    from_type: "contact",
    from_id: "con-11",
    from_name: "Kevin Zhang",
    to_type: "contact",
    to_id: "con-12",
    to_name: "Yuki Tanaka",
    relationship_type: "email_history",
    strength_score: 72,
    evidence: "Worked together at DataBricks before Kevin moved to Northstar.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-21",
    from_type: "team_member",
    from_id: "tm-4",
    from_name: "Maya Iyer",
    to_type: "contact",
    to_id: "con-5",
    to_name: "David Kim",
    relationship_type: "calendar_meeting",
    strength_score: 78,
    evidence: "Met at a16z portfolio event. Had a 1:1 discovery call.",
    source: "Google Calendar",
    last_interaction_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-22",
    from_type: "team_member",
    from_id: "tm-2",
    from_name: "Sarah Chen",
    to_type: "contact",
    to_id: "con-3",
    to_name: "Elena Rodriguez",
    relationship_type: "intro_history",
    strength_score: 88,
    evidence: "Sarah introduced Elena to a Salesforce partner intro accepted and replied.",
    source: "Gmail",
    last_interaction_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "re-23",
    from_type: "team_member",
    from_id: "tm-3",
    from_name: "Rohan Mehta",
    to_type: "contact",
    to_id: "con-6",
    to_name: "Sophie Anderson",
    relationship_type: "linkedin_connection",
    strength_score: 60,
    evidence: "Connected after a Product Hunt launch. Occasional LinkedIn interaction.",
    source: "LinkedIn",
    last_interaction_at: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_WARM_PATHS: WarmPath[] = [
  {
    id: "wp-1",
    account_id: "acc-1",
    contact_id: "con-1",
    path_nodes: [
      { id: "user-1", name: "Adhik Agarwal", type: "user" },
      { id: "tm-2", name: "Sarah Chen", type: "team_member" },
      { id: "con-1", name: "Priya Sharma", type: "contact" },
    ],
    path_explanation:
      "Sarah Chen (your advisor, ex-Salesforce) is directly connected to Priya on LinkedIn and interacted with her posts 2 weeks ago.",
    warmth_score: 87,
    confidence_score: 92,
    recommended_intro_person: "Sarah Chen",
    recommended_channel: "email",
    status: "active",
  },
  {
    id: "wp-2",
    account_id: "acc-2",
    contact_id: "con-3",
    path_nodes: [
      { id: "user-1", name: "Adhik Agarwal", type: "user" },
      { id: "tm-3", name: "Rohan Mehta", type: "team_member" },
      { id: "con-3", name: "Elena Rodriguez", type: "contact" },
    ],
    path_explanation:
      "Rohan exchanged emails with Elena at YC in 2024. Direct warm connection via email history.",
    warmth_score: 78,
    confidence_score: 85,
    recommended_intro_person: "Rohan Mehta",
    recommended_channel: "email",
    status: "intro_sent",
  },
  {
    id: "wp-3",
    account_id: "acc-4",
    contact_id: "con-7",
    path_nodes: [
      { id: "user-1", name: "Adhik Agarwal", type: "user" },
      { id: "con-7", name: "Liam Chen", type: "contact" },
    ],
    path_explanation:
      "Direct connection you met Liam at SaaStr Annual 2025 and had a follow-up call.",
    warmth_score: 91,
    confidence_score: 97,
    recommended_intro_person: "You (Adhik)",
    recommended_channel: "email",
    status: "message_sent",
  },
  {
    id: "wp-4",
    account_id: "acc-5",
    contact_id: "con-8",
    path_nodes: [
      { id: "user-1", name: "Adhik Agarwal", type: "user" },
      { id: "tm-2", name: "Sarah Chen", type: "team_member" },
      { id: "con-8", name: "Aisha Patel", type: "contact" },
    ],
    path_explanation:
      "Sarah worked with Aisha at Salesforce Data Cloud for 2 years. Close working relationship.",
    warmth_score: 88,
    confidence_score: 94,
    recommended_intro_person: "Sarah Chen",
    recommended_channel: "email",
    status: "active",
  },
  {
    id: "wp-5",
    account_id: "acc-8",
    contact_id: "con-11",
    path_nodes: [
      { id: "user-1", name: "Adhik Agarwal", type: "user" },
      { id: "tm-3", name: "Rohan Mehta", type: "team_member" },
      { id: "con-11", name: "Kevin Zhang", type: "contact" },
    ],
    path_explanation:
      "Kevin just moved to TalentGrid. Rohan had a previous demo call with him at Northstar warm champion follow-through.",
    warmth_score: 75,
    confidence_score: 88,
    recommended_intro_person: "Rohan Mehta",
    recommended_channel: "email",
    status: "active",
  },
];

export const DEMO_MESSAGES: GeneratedMessage[] = [
  {
    id: "msg-1",
    account_id: "acc-1",
    contact_id: "con-1",
    warm_path_id: "wp-1",
    signal_id: "sig-1",
    channel: "warm_intro",
    subject: "[Intro request] Priya at Acme outbound scaling question",
    body: `Hey Sarah,

Hope you're well! Quick ask I noticed you're connected to Priya Sharma (VP Sales at Acme AI).

They just posted 4 SDR roles and a RevOps Manager, which looks like they're building out their outbound motion. I'd love a quick intro we've been helping similar teams set up warm outbound at scale, and the timing seems right.

Would you be comfortable connecting us? Happy to make the ask easy on you just a "Hi Priya, you should talk to Adhik" would be plenty.

Thanks!
Adhik`,
    intro_request: `Hey Sarah mind if I mention your name when reaching out to Priya Sharma at Acme AI? They're hiring SDRs and I think WarmPath could genuinely help. Happy to make it super easy just say yes and I'll handle the rest!`,
    status: "draft",
    approval_status: "pending",
    generated_by_ai: true,
    confidence_score: 0.91,
    personalization_reason:
      "Sarah has a direct LinkedIn connection to Priya. Acme posted 4 SDR roles (high hiring signal). Tone matches Sarah's casual communication style.",
    factual_claims: [
      "Acme AI posted 4 SDR roles on LinkedIn in the last 7 days",
      "Sarah Chen is directly connected to Priya Sharma on LinkedIn",
    ],
    supporting_sources: [
      "LinkedIn Jobs (verified 2h ago)",
      "LinkedIn Connections (verified today)",
    ],
    risk_flags: [],
    contact: DEMO_CONTACTS[0],
    account: DEMO_ACCOUNTS[0],
    warm_path: DEMO_WARM_PATHS[0],
    signal: DEMO_SIGNALS[0],
  },
  {
    id: "msg-2",
    account_id: "acc-2",
    contact_id: "con-3",
    warm_path_id: "wp-2",
    signal_id: "sig-2",
    channel: "email",
    subject: "Finpilot + warm outbound saw you on the pricing page",
    body: `Hey Elena,

Rohan mentioned you two crossed paths at YC he said great things.

Noticed Finpilot visited our pricing page a couple times this week, so the timing felt right to reach out.

We help B2B SaaS teams like Finpilot turn cold outbound into warm intros specifically by mapping your team's existing relationships and routing outreach through the warmest path.

Most teams we work with see 3–4x higher reply rates vs cold email.

Would a 20-min call make sense this week? I can share a demo built around Finpilot's specific motion.

Adhik`,
    status: "draft",
    approval_status: "pending",
    generated_by_ai: true,
    confidence_score: 0.87,
    personalization_reason:
      "Website visit signal creates urgency. Rohan's YC connection adds warmth. Finpilot is FinTech ICP match. Elena is CEO decision maker.",
    factual_claims: [
      "Finpilot visited pricing page twice this week",
      "Rohan Mehta connected with Elena at YC",
    ],
    supporting_sources: [
      "Website analytics (verified today)",
      "Rohan's email history (verified in CRM)",
    ],
    risk_flags: [],
    contact: DEMO_CONTACTS[2],
    account: DEMO_ACCOUNTS[1],
    warm_path: DEMO_WARM_PATHS[1],
    signal: DEMO_SIGNALS[1],
  },
  {
    id: "msg-3",
    account_id: "acc-3",
    contact_id: "con-5",
    signal_id: "sig-3",
    channel: "email",
    subject: "Congrats on the Series A scaling outbound?",
    body: `Hi David,

Congrats on the $12M Series A impressive round, especially with Bessemer involved.

When companies at RevScale's stage raise and plan to 3x GTM, the first bottleneck is usually outbound quality. Reps get hired, sequences get built, and then reply rates disappoint.

We're building something different the first sales agent that routes outreach through your team's actual relationship graph, so every cold prospect gets a warm intro.

Would love 15 minutes to show you what that looks like in practice.

Best,
Adhik`,
    status: "draft",
    approval_status: "pending",
    generated_by_ai: true,
    confidence_score: 0.88,
    personalization_reason:
      "Recent Series A is a high-urgency trigger. Planning to 3x GTM team signals immediate need. David is CRO exact decision maker for this.",
    factual_claims: ["RevScale raised $12M Series A from Bessemer", "Plan to 3x GTM team"],
    supporting_sources: ["TechCrunch announcement (verified)"],
    risk_flags: [],
    contact: DEMO_CONTACTS[4],
    account: DEMO_ACCOUNTS[2],
    signal: DEMO_SIGNALS[2],
  },
  {
    id: "msg-4",
    account_id: "acc-4",
    contact_id: "con-7",
    warm_path_id: "wp-3",
    signal_id: "sig-4",
    channel: "email",
    subject: "Building outbound from 0 to 1 saw your post",
    body: `Hey Liam,

Great to reconnect! Saw your post about building outbound from 0 to 1 that's exactly the problem we've been obsessing over.

Most dev-tool teams try to copy enterprise playbooks (spray-and-pray) and get crushed. What works is warm routing: find which paths through your team already lead to warm intros, and only reach out through those.

Would love to show you a live demo. We can literally pull CloudNest's network and show you the warm paths right now. 15 min?

Adhik`,
    status: "draft",
    approval_status: "pending",
    generated_by_ai: true,
    confidence_score: 0.94,
    personalization_reason:
      "Direct connection from SaaStr. Liam posted publicly asking for exactly this. Offer is hyper-specific to his stated challenge.",
    factual_claims: ["Liam Chen posted on LinkedIn about building outbound from 0 to 1"],
    supporting_sources: ["LinkedIn post (verified 4h ago)"],
    risk_flags: [],
    contact: DEMO_CONTACTS[6],
    account: DEMO_ACCOUNTS[3],
    warm_path: DEMO_WARM_PATHS[2],
    signal: DEMO_SIGNALS[3],
  },
  {
    id: "msg-5",
    account_id: "acc-7",
    contact_id: "con-10",
    signal_id: "sig-7",
    channel: "email",
    subject: "Building your sales team at BrightOps warm outbound angle",
    body: `Hi Rachel,

I've been following BrightOps the positioning around RevOps automation is sharp.

Noticed you're hiring 3 AEs and a Sales Engineer, which tells me you're building an outbound motion from scratch. That's exactly the moment where the tools you choose matter most.

We've built the first sales agent that routes every prospect through your team's existing relationship graph so your new AEs aren't starting cold on day one.

Happy to show you a 15-min demo. We can even map BrightOps' relationship graph live to show you where the warm paths already exist.

Adhik`,
    status: "approved",
    approval_status: "approved",
    generated_by_ai: true,
    confidence_score: 0.89,
    personalization_reason:
      "BrightOps is a RevOps company perfect ICP. Hiring signal shows immediate need. Rachel is CEO building sales from scratch.",
    factual_claims: ["BrightOps posted 3 AE roles and a Sales Engineer on LinkedIn"],
    supporting_sources: ["LinkedIn Jobs (verified 6h ago)"],
    risk_flags: [],
    contact: DEMO_CONTACTS[9],
    account: DEMO_ACCOUNTS[6],
    signal: DEMO_SIGNALS[6],
  },
];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-1",
    user_id: "user-1",
    name: "Series A Funded Companies GTM Scaling",
    goal: "Book discovery calls with recently-funded B2B SaaS companies building outbound",
    status: "active",
    target_segment: "Series A companies in B2B SaaS, 50–250 employees, hiring SDRs",
    channels: ["email", "linkedin"],
    created_at: "2026-04-01T09:00:00Z",
    steps: [
      {
        id: "cs-1",
        campaign_id: "camp-1",
        step_number: 1,
        channel: "warm_intro",
        delay_days: 0,
        template_type: "warm_intro_request",
        template_hint: "Ask team member for warm intro reference shared context",
        objective: "Ask team member for intro via warm path",
        is_ai_generated: true,
      },
      {
        id: "cs-2",
        campaign_id: "camp-1",
        step_number: 2,
        channel: "email",
        delay_days: 2,
        template_type: "prospect_outreach",
        template_hint: "Reference the intro, lead with Series A angle",
        objective: "Warm outreach to prospect after intro granted",
        is_ai_generated: true,
      },
      {
        id: "cs-3",
        campaign_id: "camp-1",
        step_number: 3,
        channel: "linkedin",
        delay_days: 4,
        template_type: "linkedin_dm",
        template_hint: "Short DM referencing email keep it under 3 sentences",
        objective: "LinkedIn follow-up if no email reply",
        is_ai_generated: true,
      },
      {
        id: "cs-4",
        campaign_id: "camp-1",
        step_number: 4,
        channel: "email",
        delay_days: 7,
        template_type: "value_add",
        template_hint: "Share a relevant case study or data point",
        objective: "Share relevant case study or insight",
        is_ai_generated: true,
      },
      {
        id: "cs-5",
        campaign_id: "camp-1",
        step_number: 5,
        channel: "email",
        delay_days: 14,
        template_type: "breakup",
        template_hint: "Permission-based breakup leave door open",
        objective: "Breakup email last touch",
        is_ai_generated: true,
      },
    ],
    stats: {
      total_prospects: 24,
      messages_sent: 18,
      replies: 7,
      meetings_booked: 3,
      reply_rate: 38.9,
      meeting_rate: 16.7,
    },
  },
  {
    id: "camp-2",
    user_id: "user-1",
    name: "Hiring Signal SDR & RevOps Roles",
    goal: "Reach companies actively hiring sales/RevOps talent as a buying signal",
    status: "active",
    target_segment: "Companies hiring 2+ SDRs or RevOps roles in the last 30 days",
    channels: ["email"],
    created_at: "2026-04-10T09:00:00Z",
    steps: [
      {
        id: "cs-6",
        campaign_id: "camp-2",
        step_number: 1,
        channel: "email",
        delay_days: 0,
        template_type: "prospect_outreach",
        template_hint: "Lead with hiring signal 'noticed you're building outbound'",
        objective: "Signal-triggered first touch referencing hiring",
        is_ai_generated: true,
      },
      {
        id: "cs-7",
        campaign_id: "camp-2",
        step_number: 2,
        channel: "email",
        delay_days: 5,
        template_type: "follow_up",
        template_hint: "Add a customer proof point, keep it brief",
        objective: "Follow-up with social proof",
        is_ai_generated: true,
      },
    ],
    stats: {
      total_prospects: 31,
      messages_sent: 28,
      replies: 9,
      meetings_booked: 2,
      reply_rate: 32.1,
      meeting_rate: 7.1,
    },
  },
  {
    id: "camp-3",
    user_id: "user-1",
    name: "Champion Tracking Job Change Reactivation",
    goal: "Reach out to past champions who moved to new companies",
    status: "draft",
    target_segment: "Contacts from past deals who changed jobs in the last 60 days",
    channels: ["email", "linkedin"],
    created_at: "2026-04-20T09:00:00Z",
    steps: [
      {
        id: "cs-8",
        campaign_id: "camp-3",
        step_number: 1,
        channel: "email",
        delay_days: 0,
        template_type: "champion_reactivation",
        template_hint: "Congratulate on new role, reference past relationship naturally",
        objective: "Warm reconnect at new company",
        is_ai_generated: true,
      },
    ],
    stats: {
      total_prospects: 8,
      messages_sent: 0,
      replies: 0,
      meetings_booked: 0,
      reply_rate: 0,
      meeting_rate: 0,
    },
  },
];

export const DEMO_INTERACTIONS: Interaction[] = [
  {
    id: "int-1",
    account_id: "acc-1",
    contact_id: "con-1",
    type: "signal",
    summary: "Acme AI posted 4 SDR roles hiring signal detected",
    channel: "LinkedIn",
    occurred_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "int-2",
    account_id: "acc-2",
    type: "signal",
    summary: "Finpilot visited pricing page (2nd visit this week)",
    channel: "Website",
    occurred_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "int-3",
    account_id: "acc-3",
    type: "signal",
    summary: "RevScale announced $12M Series A",
    channel: "News",
    occurred_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "int-4",
    account_id: "acc-7",
    contact_id: "con-10",
    type: "email_sent",
    summary: "Warm outreach email sent to Rachel Green (approved)",
    channel: "Email",
    occurred_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_SUBSCRIPTION: Subscription = {
  id: "sub-1",
  user_id: "user-1",
  plan: "growth",
  status: "active",
  current_period_end: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
  usage_contacts: 127,
  usage_messages: 43,
};

export const DEMO_NEXT_BEST_ACTIONS: NextBestAction[] = [
  {
    account: "Acme AI",
    account_id: "acc-1",
    contact: "Priya Sharma",
    contact_id: "con-1",
    reason:
      "Acme is hiring 4 SDRs. Sarah Chen has a direct LinkedIn connection to Priya. High urgency signal + strong warm path.",
    recommended_channel: "email",
    recommended_action: "Ask Sarah for intro, then send warm email to Priya",
    confidence: 0.92,
    urgency: "high",
  },
  {
    account: "RevScale",
    account_id: "acc-3",
    contact: "David Kim",
    contact_id: "con-5",
    reason:
      "RevScale just raised $12M Series A with plans to 3x GTM. Budget is unlocked, urgency is real. Strike within 48h of announcement.",
    recommended_channel: "email",
    recommended_action: "Send congratulatory cold email funding window closes fast",
    confidence: 0.88,
    urgency: "high",
  },
  {
    account: "CloudNest",
    account_id: "acc-4",
    contact: "Liam Chen",
    contact_id: "con-7",
    reason:
      "Liam posted publicly asking for help with outbound. You met him at SaaStr direct connection. Reply now while the post is fresh.",
    recommended_channel: "email",
    recommended_action:
      "Follow up directly you have a personal connection and he's asking for help",
    confidence: 0.94,
    urgency: "high",
  },
  {
    account: "TalentGrid",
    account_id: "acc-8",
    contact: "Kevin Zhang",
    contact_id: "con-11",
    reason:
      "Kevin (past champion from Northstar) just moved to TalentGrid as VP Sales. Fresh start at new company = high receptiveness.",
    recommended_channel: "email",
    recommended_action: "Rohan should reach out he had a prior demo call with Kevin",
    confidence: 0.86,
    urgency: "medium",
  },
];
